### ISSUE TITLE
Out of the box

### ISSUE THREAD

**Issue by flowerbug** [Fenekito/Roguelike-Engine#1]
Hello, I just gave this a try and my comment is that as a default either include the needed sounds with the code or don't error off if the sounds are not provided.

Just to play around I created a bunch of empty sounds and then had to change one line of code for your code to work for me.

I commented out 

        SoundHandler.BGMHandler(self.current_floor)

in game_map.py as the code was giving me an error about the mp3 i was using.

**Comment by Fenekito** [comment]
Hello, thanks for trying the engine. 
Sounds are now included out of the box, sorry for the incovenience this has caused.
